trigger:
  - master

pool:
  vmImage: ubuntu-latest

variables:
  system.debug: true
  TargetDir: $GOPATH/src/github.com/terraform-providers/terraform-provider-incapsula

jobs:
- job: build
  container: docker.io/golang:1.13
  steps:
    - checkout: self
      clean: true
    - script: |
        echo $GOPATH
        cp -r $(Build.SourcesDirectory) $(TargetDir)
        cd $(TargetDir)
        make bin
        ls -R $GOPATH/bin
        make test
    - publish: $(TargetDir)/bin
      artifact: drop