trigger:
  - master

pool:
  vmImage: ubuntu-latest

variables:
  system.debug: true
  GOFLAGS: -mod=vendor
  WorkingDir: /go/src/github.com/terraform-providers/terraform-provider-incapsula

jobs:
- job: build
  container: 
    image: docker.io/golang:1.13
  steps:
    - checkout: self
      clean: true
    - script: cp -r $(Build.SourcesDirectory) $(WorkingDir)
    # - script: $(WorkingDir)/scripts/gogetcookie.sh
    - bash: make build
      workingDirectory: $(WorkingDir)
    - bash: make test
      workingDirectory: $(WorkingDir)
    - bash: make vet
      workingDirectory: $(WorkingDir)
    - publish: /go/bin/terraform-provider-incapsula
      artifact: drop