trigger:
  - master
  - feature/*

pool:
  vmImage: ubuntu-latest

variables:
  system.debug: true
  GOFLAGS: -mod=vendor
  WorkingDir: /go/src/github.com/terraform-providers/terraform-provider-incapsula

jobs:
- job: build
  container: 
    image: docker.io/golang:1.13
  steps:
    - checkout: self
      clean: true
    - bash: mkdir -p $(WorkingDir)
    - bash: cp -r $(Build.SourcesDirectory)/** $(WorkingDir)
    # - bash: $(WorkingDir)/scripts/gogetcookie.sh
    - bash: make build
      workingDirectory: $(WorkingDir)
    - bash: make test
      workingDirectory: $(WorkingDir)
    - bash: make vet
      workingDirectory: $(WorkingDir)
    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: /go/bin/terraform-provider-incapsula
        artifactName: drop