trigger:
  - master

pool:
  vmImage: ubuntu-latest

variables:
  system.debug: true
  GOFLAGS: -mod=vendor

jobs:
- job: build
  container: docker.io/golang:1.13
  steps:
    - checkout: self
      clean: true
    - script: $(Build.SourcesDirectory)/scripts/gogetcookie.sh
    - script: make build
    - script: make test
    - script: make vet
    # - publish: $(Build.SourcesDirectory)/bin
    #   artifact: drop